package main

import (
	"testing"
)

func TestEssSlew(t *testing.T) {

	testCases := []map[string]interface{}{
		// test cases for Active power Ramp Rate testing
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1966.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         3.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test using Ramp Rise Rate  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            3.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1950.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test with different deltaT  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1966.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test with both Ramp Rise and Ramp Drop Rates active  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 10000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         5.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            4.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   5000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test with a large value  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1033.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   2000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test using Ramp Drop Rate  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            3.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1050.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test with different deltaT  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1033.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test with both Ramp Rise and Ramp Drop Rates active  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 0.0,
			"targetPcmd":        10000.0,
			"targetQcmd":        0.0,
			"Pramprise":         5.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            30.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   3500.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test with a large value  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         2.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  true,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   166.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         2.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   66.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test using Ramp Rise Rate  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         2.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test using Ramp Drop Rate  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   166.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test with both Ramp Rise and Ramp Drop Rates active  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        5.0,
			"Prampstop":         1.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   166.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test with Ramp Stop, Ramp Start, and Ramp Drop Rates active  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1833.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test using Ramp Rise Rate  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test using Ramp Drop Rate  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1833.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test with both Ramp Rise and Ramp Drop Rates active  Active power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1833.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test with Ramp Start, Ramp Rise, and Ramp Drop Rates  Active power Ramp Rate testing",
		},
		// test cases for Reactive power Ramp Rate testing
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 2000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test  Reactive power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 2000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test with both Ramp Rise and Ramp Drop Rates active  Reactive power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 10000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            4.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         10.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   5000.0,
			"comment":           "Ramp Drop Test with a large value  Reactive power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        2000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test  Reactive power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        2000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test with both Ramp Rise and Ramp Drop Rates active  Reactive power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        10000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            30.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   2500.0,
			"comment":           "Ramp Rise Test with a large value  Reactive power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        10000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1166.67,
			"comment":           "Ramp Start Test  Reactive power Ramp Rate testing",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         8.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   166.67,
			"comment": "Ramp Start Test with Ramp Stop, Ramp Start, and Ramp Drop Rates active		Reactive power Ramp Rate testing",
		},
		// test cases with both Reactive power ramping active and Active power ramping active
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 2000.0,
			"Q":                 2000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        true,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1933.33,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 2000.0,
			"Q":                 2000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         5.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1933.33,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test with both Ramp Rise and Ramp Drop Rates active  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 10000.0,
			"Q":                 10000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         15.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            4.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         10.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   5000.0,
			"QexpectedResult":   5000.0,
			"comment":           "Ramp Drop Test with a large value  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         5.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1166.67,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         5.0,
			"Prampdrop":         3.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1166.67,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test with  both Ramp Rise and Ramp Drop Rates active both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 1000.0,
			"targetPcmd":        10000.0,
			"targetQcmd":        10000.0,
			"Pramprise":         10.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            30.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   5000.0,
			"QexpectedResult":   2500.0,
			"comment":           "Ramp Rise Test with a large value  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        3.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  true,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1100.0,
			"QexpectedResult":   1166.67,
			"comment":           "Ramp Start Test  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         2.0,
			"Prampdrop":         3.0,
			"Prampstart":        4.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         8.0,
			"PexpectedResult":   133.33,
			"QexpectedResult":   166.67,
			"comment":           "Ramp Start Test with Ramp Stop, Ramp Start, and Ramp Drop Rates active  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 1000.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   true,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   833.33,
			"QexpectedResult":   933.33,
			"comment":           "Ramp Stop Test  both Reactive power ramping active and Active power ramping active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 2000.0,
			"Q":                 2000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         3.0,
			"Prampstart":        2.0,
			"Prampstop":         2.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        2.0,
			"Qramprise":         3.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   1933.33,
			"QexpectedResult":   1933.33,
			"comment":           "Ramp Stop Test with Ramp Start, Ramp Rise, and Ramp Drop Rates  both Reactive power ramping active and Active power ramping active",
		},
		// test cases for percentage maximum power per second conversion
		{
			"AbsRampRate":       false,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         2.0,
			"Prampdrop":         3.0,
			"Prampstart":        4.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         8.0,
			"PexpectedResult":   400.0,
			"QexpectedResult":   500.0,
			"comment":           "Ramp Start Test  percentage maximum power per second conversion",
		},
		{
			"AbsRampRate":       false,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         5.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1500.0,
			"QexpectedResult":   1200.0,
			"comment":           "Ramp Rise Test  percentage maximum power per second conversion",
		},
		{
			"AbsRampRate":       false,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"P":                 2000.0,
			"Q":                 2000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1800.0,
			"QexpectedResult":   1500.0,
			"comment":           "Ramp Drop Test  percentage maximum power per second conversion",
		},
		{
			"AbsRampRate":       false,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"P":                 1000.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   true,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   500.0,
			"QexpectedResult":   800.0,
			"comment":           "Ramp Stop Test  percentage maximum power per second conversion",
		},
	}

	var e ess          // instance of the ess class
	var input terminal // dummy input terminal

	// initialize values for testing on pcs
	for _, entry := range testCases {
		e.AbsRampRate = entry["AbsRampRate"].(bool)
		e.On = entry["powerInitialState"].(bool)
		e.Oncmd = entry["oncmd"].(bool)
		e.Offcmd = entry["offcmd"].(bool)
		e.Soc = 50
		e.Phigh = 5000
		e.Qhigh = 5000
		e.Pcharge = e.Phigh
		e.Pdischarge = e.Phigh
		e.Cap = 2000
		e.AcContactorCloseCmd = true
		e.DcContactorCloseCmd = true
		e.AcContactor = e.On
		e.DcContactor = e.On
		e.GridForming = false
		e.P = entry["P"].(float64)
		e.Q = entry["Q"].(float64)
		e.Pcmd = entry["targetPcmd"].(float64)
		e.Qcmd = entry["targetQcmd"].(float64)

		// these guys
		e.PRampRise = entry["Pramprise"].(float64)
		e.PRampDrop = entry["Prampdrop"].(float64)
		e.PRampStart = entry["Prampstart"].(float64)
		e.PRampStop = entry["Prampstop"].(float64)

		e.PRampDropEnable = entry["PRampDropEnable"].(bool)
		e.PRampRiseEnable = entry["PRampRiseEnable"].(bool)
		e.PRampStartEnable = entry["PRampStartEnable"].(bool)
		e.PRampStopEnable = entry["PRampStopEnable"].(bool)

		// us too
		e.RampEnable = entry["RampEnable"].(bool)
		e.QRampStart = entry["Qrampstart"].(float64)
		e.QRampRise = entry["Qramprise"].(float64)
		e.QRampDrop = entry["Qrampdrop"].(float64)
		e.QRampStop = entry["Qrampstop"].(float64)

		e.QRampStartEnable = entry["QRampStartEnable"].(bool)
		e.QRampRiseEnable = entry["QRampRiseEnable"].(bool)
		e.QRampDropEnable = entry["QRampDropEnable"].(bool)
		e.QRampStopEnable = entry["QRampStopEnable"].(bool)
		e.QstopActive = false
		e.QstartActive = false

		// fmt.Println("\n Test: ", entry["comment"].(string))
		(&e).Init()
		if entry["P"].(float64) > entry["targetPcmd"].(float64) {
			input.p = entry["P"].(float64)
		} else {
			input.p = entry["targetPcmd"].(float64)
		}

		_ = (&e).UpdateMode(input)
		// fmt.Println("[After UpdateMode]", "e.on", e.On, "e.AcContactor", e.AcContactor, "e.DcContactor", e.DcContactor)
		_ = (&e).CalculateState(input, entry["deltaT"].(float64))
		_ = (&e).UpdateState(input, entry["deltaT"].(float64))
		if !(entry["PexpectedResult"].(float64)*1.01 >= e.P && entry["PexpectedResult"].(float64)*0.99 <= e.P) {
			t.Log("Incorrect Ramprate used on Test: ", entry["comment"].(string))
			t.Logf("Got %.2f expected %.2f", e.P, entry["PexpectedResult"].(float64))
			t.Fail()
		}

		if !(entry["QexpectedResult"].(float64)*1.01 >= e.Q && entry["QexpectedResult"].(float64)*0.99 <= e.Q) {
			t.Log("Incorrect Ramprate used on Test:", entry["comment"].(string))
			t.Logf("Got %.2f expected %.2f", e.Q, entry["QexpectedResult"].(float64))
			t.Fail()
		}
	}
}
