#!/usr/bin/env groovy
//See package_utility/README for a list of valid inputs
myJobPipeline {
    //When would you like to trigger?
    buildTrigger="prOnly"
    //Which OS would you like to build on?
    imageNames=["centos7"]
    //Does the image need a special tag?
    imageTag="base"
    //Run unit tests?
    unitTestStage=false
    //Run regression Tests?
    regTestStage=false
    //Which repository will RPMs be uploaded to?
    uploadRepo="infrastructure"
    //Will a release of this repo need to trigger a docker image build?
    dockerBuild=false
    dockerImageName=""
    dockerTag=""
}