package main

import (
	"testing"
)

func TestPcsSlew(t *testing.T) {

	testCases := []map[string]interface{}{
		// test cases for Active power Ramp Rate testing
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1966.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         3.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test using Ramp Rise Rate",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            3.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1950.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test with different deltaT",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1966.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               10000.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         5.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            4.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   5000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Drop Test with a large value",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1033.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   2000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test using Ramp Drop Rate",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         1.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            3.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1050.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test with different deltaT",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         1.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1033.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 0.0,
			"targetPcmd":        10000.0,
			"targetQcmd":        0.0,
			"Pramprise":         5.0,
			"Prampdrop":         5.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            30.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   3500.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Rise Test with a large value",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         2.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  true,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   166.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         2.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   66.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test using Ramp Rise Rate",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         2.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1000.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test using Ramp Drop Rate",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        5.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   166.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        5.0,
			"Prampstop":         1.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   166.67,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Start Test with Ramp Stop, Ramp Start, and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1833.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test using Ramp Rise Rate",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test using Ramp Drop Rate",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1833.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               2000.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         3.0,
			"Prampdrop":         3.0,
			"Prampstart":        1.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1833.33,
			"QexpectedResult":   0.0,
			"comment":           "Ramp Stop Test with Ramp Start, Ramp Rise, and Ramp Drop Rates",
		},
		// test cases for Reactive power Ramp Rate testing
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 2000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 2000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 10000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            4.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         10.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   5000.0,
			"comment":           "Ramp Drop Test with a large value",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        2000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        2000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        10000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            30.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   2500.0,
			"comment":           "Ramp Rise Test with a large value",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        2000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1166.67,
			"comment":           "Ramp Start Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        0.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         8.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   166.67,
			"comment":           "Ramp Start Test with Ramp Stop, Ramp Start, and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               0.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   true,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   933.33,
			"comment":           "Ramp Stop Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               0.0,
			"Q":                 2000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        2.0,
			"Qramprise":         3.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   0.0,
			"QexpectedResult":   1933.33,
			"comment":           "Ramp Stop Test with Ramp Start, Ramp Rise, and Ramp Drop Rates",
		},
		// test cases with both Reactive power ramping active and Active power ramping active
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               2000.0,
			"Q":                 2000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1933.33,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               2000.0,
			"Q":                 2000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         5.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1933.33,
			"QexpectedResult":   1833.33,
			"comment":           "Ramp Drop Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               10000.0,
			"Q":                 10000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         15.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            4.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         10.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   5000.0,
			"QexpectedResult":   5000.0,
			"comment":           "Ramp Drop Test with a large value",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         5.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1166.67,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         5.0,
			"Prampdrop":         3.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1166.67,
			"QexpectedResult":   1066.67,
			"comment":           "Ramp Rise Test with both Ramp Rise and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 1000.0,
			"targetPcmd":        10000.0,
			"targetQcmd":        10000.0,
			"Pramprise":         10.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            30.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         3.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   5000.0,
			"QexpectedResult":   2500.0,
			"comment":           "Ramp Rise Test with a large value",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        3.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  true,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1100.0,
			"QexpectedResult":   1166.67,
			"comment":           "Ramp Start Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         2.0,
			"Prampdrop":         3.0,
			"Prampstart":        4.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         8.0,
			"PexpectedResult":   133.33,
			"QexpectedResult":   166.67,
			"comment":           "Ramp Start Test with Ramp Stop, Ramp Start, and Ramp Drop Rates active",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               1000.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   true,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   833.33,
			"QexpectedResult":   933.33,
			"comment":           "Ramp Stop Test",
		},
		{
			"AbsRampRate":       true,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               2000.0,
			"Q":                 2000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         2.0,
			"Prampdrop":         3.0,
			"Prampstart":        2.0,
			"Prampstop":         2.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        2.0,
			"Qramprise":         3.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   1933.33,
			"QexpectedResult":   1933.33,
			"comment":           "Ramp Stop Test with Ramp Start, Ramp Rise, and Ramp Drop Rates",
		},
		// test cases for percentage maximum power per second conversion
		{
			"AbsRampRate":       false,
			"powerInitialState": false,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               0.0,
			"Q":                 0.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         2.0,
			"Prampdrop":         3.0,
			"Prampstart":        4.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  true,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  true,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   true,
			"QRampStopEnable":   true,
			"Qrampstart":        5.0,
			"Qramprise":         2.0,
			"Qrampdrop":         3.0,
			"Qrampstop":         8.0,
			"PexpectedResult":   400.0,
			"QexpectedResult":   500.0,
			"comment":           "Ramp Start Test",
		},
		{
			"AbsRampRate":       false,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               1000.0,
			"Q":                 1000.0,
			"targetPcmd":        2000.0,
			"targetQcmd":        2000.0,
			"Pramprise":         5.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   true,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   true,
			"QRampDropEnable":   false,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         2.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1500.0,
			"QexpectedResult":   1200.0,
			"comment":           "Ramp Rise Test",
		},
		{
			"AbsRampRate":       false,
			"powerInitialState": true,
			"oncmd":             true,
			"offcmd":            false,
			"Pdc":               2000.0,
			"Q":                 2000.0,
			"targetPcmd":        1000.0,
			"targetQcmd":        1000.0,
			"Pramprise":         0.0,
			"Prampdrop":         2.0,
			"Prampstart":        0.0,
			"Prampstop":         0.0,
			"deltaT":            2.0,
			"PRampDropEnable":   true,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   false,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   true,
			"QRampStopEnable":   false,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         5.0,
			"Qrampstop":         0.0,
			"PexpectedResult":   1800.0,
			"QexpectedResult":   1500.0,
			"comment":           "Ramp Drop Test",
		},
		{
			"AbsRampRate":       false,
			"powerInitialState": true,
			"oncmd":             false,
			"offcmd":            true,
			"Pdc":               1000.0,
			"Q":                 1000.0,
			"targetPcmd":        0.0,
			"targetQcmd":        0.0,
			"Pramprise":         0.0,
			"Prampdrop":         0.0,
			"Prampstart":        0.0,
			"Prampstop":         5.0,
			"deltaT":            2.0,
			"PRampDropEnable":   false,
			"PRampRiseEnable":   false,
			"PRampStartEnable":  false,
			"PRampStopEnable":   true,
			"RampEnable":        false,
			"QRampStartEnable":  false,
			"QRampRiseEnable":   false,
			"QRampDropEnable":   false,
			"QRampStopEnable":   true,
			"Qrampstart":        0.0,
			"Qramprise":         0.0,
			"Qrampdrop":         0.0,
			"Qrampstop":         2.0,
			"PexpectedResult":   500.0,
			"QexpectedResult":   800.0,
			"comment":           "Ramp Stop Test",
		},
	}

	var p pcs          // instance of the pcs class
	var input terminal // dummy input terminal

	// initialize values for testing on pcs
	for _, entry := range testCases {
		p.AbsRampRate = entry["AbsRampRate"].(bool)
		p.On = entry["powerInitialState"].(bool)
		p.Oncmd = entry["oncmd"].(bool)
		p.Offcmd = entry["offcmd"].(bool)
		p.Plim = 5000
		p.Qlim = 5000
		p.AcContactorCloseCmd = true
		p.DcContactorCloseCmd = true
		p.GridForming = false
		p.Pdc = entry["Pdc"].(float64)
		p.Q = entry["Q"].(float64)
		p.Pcmd = entry["targetPcmd"].(float64)
		p.Qcmd = entry["targetQcmd"].(float64)
		p.PRampRise = entry["Pramprise"].(float64)
		p.PRampDrop = entry["Prampdrop"].(float64)
		p.PRampStart = entry["Prampstart"].(float64)
		p.PRampStop = entry["Prampstop"].(float64)
		p.PRampDropEnable = entry["PRampDropEnable"].(bool)
		p.PRampRiseEnable = entry["PRampRiseEnable"].(bool)
		p.PRampStartEnable = entry["PRampStartEnable"].(bool)
		p.PRampStopEnable = entry["PRampStopEnable"].(bool)
		p.RampEnable = entry["RampEnable"].(bool)
		p.QRampStart = entry["Qrampstart"].(float64)
		p.QRampRise = entry["Qramprise"].(float64)
		p.QRampDrop = entry["Qrampdrop"].(float64)
		p.QRampStop = entry["Qrampstop"].(float64)
		p.QRampStartEnable = entry["QRampStartEnable"].(bool)
		p.QRampRiseEnable = entry["QRampRiseEnable"].(bool)
		p.QRampDropEnable = entry["QRampDropEnable"].(bool)
		p.QRampStopEnable = entry["QRampStopEnable"].(bool)

		// fmt.Println("\n Test: ", entry["comment"].(string))
		(&p).Init()
		if entry["Pdc"].(float64) > entry["targetPcmd"].(float64) {
			input.p = entry["Pdc"].(float64)
		} else {
			input.p = entry["targetPcmd"].(float64)
		}

		_ = (&p).UpdateMode(input)
		// fmt.Println("[After UpdateMode]","p.on", p.On, "p.AcContactor", p.AcContactor, "P.DcContactor", p.DcContactor)
		_ = (&p).CalculateState(input, entry["deltaT"].(float64))
		_ = (&p).UpdateState(input, entry["deltaT"].(float64))
		if !(entry["PexpectedResult"].(float64)*1.01 >= p.Pdc && entry["PexpectedResult"].(float64)*0.99 <= p.Pdc) {
			t.Log("Incorrect Ramprate used for test: ", entry["comment"].(string))
			t.Logf("Got %.2f expected %.2f", p.Pdc, entry["PexpectedResult"].(float64))
			t.Fail()
		}

		if !(entry["QexpectedResult"].(float64)*1.01 >= p.Q && entry["QexpectedResult"].(float64)*0.99 <= p.Q) {
			t.Log("Incorrect Ramprate used for test: ", entry["comment"].(string))
			t.Logf("Got %.2f expected %.2f", p.Q, entry["QexpectedResult"].(float64))
			t.Fail()
		}
	}
}
