version: 11.3.1.alpha.1
dnp3_server:
  sel_411l_dnp3_server.json:
    ip: 0.0.0.0
    port: 502
  sel_487e_dnp3_server.json:
    ip: 0.0.0.0
    port: 503
modbus_server:
  apc_ups_modbus_server.json:
    ip: 0.0.0.0
    port: 504
  ess_10_modbus_server.json:
    ip: 0.0.0.0
    port: 505
  ess_11_modbus_server.json:
    ip: 0.0.0.0
    port: 506
  ess_12_modbus_server.json:
    ip: 0.0.0.0
    port: 507
  ess_1_bms_modbus_server.json:
    ip: 0.0.0.0
    port: 508
  ess_1_pcs_modbus_server.json:
    ip: 0.0.0.0
    port: 509
  ess_2_modbus_server.json:
    ip: 0.0.0.0
    port: 510
  ess_3_modbus_server.json:
    ip: 0.0.0.0
    port: 511
  ess_4_modbus_server.json:
    ip: 0.0.0.0
    port: 512
  ess_5_modbus_server.json:
    ip: 0.0.0.0
    port: 513
  ess_6_modbus_server.json:
    ip: 0.0.0.0
    port: 514
  ess_7_modbus_server.json:
    ip: 0.0.0.0
    port: 515
  ess_8_modbus_server.json:
    ip: 0.0.0.0
    port: 516
  ess_9_modbus_server.json:
    ip: 0.0.0.0
    port: 517
  sel_2440_modbus_server.json:
    ip: 0.0.0.0
    port: 518
  sel_351_1_modbus_server.json:
    ip: 0.0.0.0
    port: 519
  sel_351_2_modbus_server.json:
    ip: 0.0.0.0
    port: 520
  sel_735_modbus_server.json:
    ip: 0.0.0.0
    port: 521
