import { SystemStatusObject } from './SystemStatus.types';

export const statusColorMapping: {
  [key: string]: 'error' | 'primary' | 'warning' | 'success' | 'inherit' | 'secondary' | 'disabled' | 'action' | 'info' | undefined
} = {
  failed: 'error',
  initialized: 'primary',
  stopped: 'warning',
  active: 'success',
  reloading: 'primary',
  inactive: 'warning',
  activating: 'primary',
  deactivating: 'primary',
};

export const initialSystemStatusFilter = {
  serviceNames: [],
  serviceStatus: [],
  connectionStatus: [],
};

export const mockSystemStatusData: SystemStatusObject[] = [
  {
    dependencies: [],
    serviceName: 'site_controller',
    serviceStatus: 'Active (Running)',
    connectionStatus: 'offline',
    cpuUsage: 20,
    memoryUsage: 21,
    uptime: '01:20:45:00',
    lastRestart: '01/13/23 16:20:21',
    actions: ['start', 'stop', 'restart'],
  },
  {
    dependencies: ['site_controller', 'fims'],
    serviceName: 'modbus_controller_01',
    serviceStatus: 'Stopped',
    connectionStatus: 'online',
    cpuUsage: 2,
    memoryUsage: 17,
    uptime: '00:18:30:25',
    lastRestart: '01/12/23 16:20:21',
    actions: ['restart'],
  },
  {
    dependencies: [],
    serviceName: 'fims',
    serviceStatus: 'Active (Auto Restart)',
    connectionStatus: 'offline',
    cpuUsage: 10,
    memoryUsage: 9,
    uptime: '01:20:45:00',
    lastRestart: '01/13/23 16:20:21',
    actions: ['start', 'stop', 'restart'],
  },
  {
    dependencies: ['site_controller', 'fims'],
    serviceName: 'ess_controller',
    serviceStatus: 'Initialized',
    connectionStatus: 'online',
    cpuUsage: 15,
    memoryUsage: 18,
    uptime: '00:18:30:25',
    lastRestart: '01/12/23 16:20:21',
    actions: ['restart', 'stop'],
  },
  {
    dependencies: [],
    serviceName: 'fleet_manager',
    serviceStatus: 'Active (Auto Restart)',
    connectionStatus: 'offline',
    cpuUsage: 7,
    memoryUsage: 10,
    uptime: '01:20:45:00',
    lastRestart: '01/13/23 16:20:21',
    actions: ['start', 'stop', 'restart'],
  },
  {
    dependencies: ['site_controller', 'fims'],
    serviceName: 'modbus_controller_02',
    serviceStatus: 'Stopped',
    connectionStatus: 'online',
    cpuUsage: 6,
    memoryUsage: 7,
    uptime: '00:18:30:25',
    lastRestart: '01/12/23 16:20:21',
    actions: ['start', 'restart'],
  },
  {
    dependencies: ['site_controller', 'fims'],
    serviceName: 'ess_controller_02',
    serviceStatus: 'Initialized',
    connectionStatus: 'online',
    cpuUsage: 30,
    memoryUsage: 24,
    uptime: '00:18:30:25',
    lastRestart: '01/12/23 16:20:21',
    actions: ['restart'],
  },
  {
    dependencies: [],
    serviceName: 'modbus_controller_03',
    serviceStatus: 'Active (Running)',
    connectionStatus: 'offline',
    cpuUsage: 12,
    memoryUsage: 12,
    uptime: '01:20:45:00',
    lastRestart: '01/13/23 16:20:21',
    actions: ['start', 'stop', 'restart'],
  },
  {
    dependencies: ['site_controller', 'fims'],
    serviceName: 'modbus_client',
    serviceStatus: 'Failed',
    connectionStatus: 'online',
    cpuUsage: 3,
    memoryUsage: 2,
    uptime: '00:18:30:25',
    lastRestart: '01/12/23 16:20:21',
    actions: ['restart'],
  },
];
