@load_to_dbi_server
Feature: load_to_dbi_server

  Scenario:
    Given mongo and dbi are running
    And I clear all data in dbi/test_client
    And I clear all data in dbi/test_server
    And modbus_client is running the config test_load_to_from_dbi_client.json
    And modbus_server is running the config test_load_to_from_dbi_server.json
    And I am listening for a fims set on /dbi
    And I am listening for a fims get on /dbi
    And I am listening for a fims set on /components/test_server
    And I am listening for a fims pub on /components/test_client
    And I am listening for a fims set on /interfaces/test_server
    When I wait 2 seconds
    And I send a fims pub to /components/test_server containing
      """
      {
          "hold_1_1": 1,
          "hold_1_2": 2,
          "hold_1_4": 3,
          "hold_2_1": 4,
          "hold_2_2": 5,
          "hold_2_4": 6,
          "shold_1_1": 7,
          "shold_1_2": 8,
          "shold_1_4": 9,
          "shold_2_1": 10,
          "shold_2_2": 11,
          "shold_2_4": 12,
          "fhold_1_2": 13.7,
          "fhold_1_4": 14.8,
          "scale_1_1": 16,
          "scale_1_2": 17,
          "scale_1_4": 18,
          "shift_1_1": 19,
          "shift_1_2": 20,
          "shift_1_4": 21,
          "test_id": 22,
          "inv_1_16": 23,
          "inv_1_4": 24,
          "multi_1": 25,
          "multi_2": 26,
          "multi_3": 27,
          "multi_4": 28,
          "multi_5": 29,
          "multi_6": 30,
          "multi_7": 31,
          "multi_8": 32,
          "multi_9": 33,
          "multi_10": 34,
          "multi_11": 35,
          "multi_12": 36,
          "multi_13": 37,
          "debounce_1": 38,
          "error_1": 39,
          "input_0_1": 40,
          "input_1_1": 41,
          "input_2_1": 42,
          "input_3_1": 43,
          "sinput_4_1": 44,
          "input_5_1": 45,
          "input_7_1": 46,
          "input_0_2": 47,
          "input_1_2": 48,
          "input_2_2": 49,
          "input_3_2": 50,
          "sinput_4_2": 51,
          "input_5_2": 52,
          "finput_6_2": 53.6,
          "input_7_2": 54,
          "input_0_4": 55,
          "input_1_4": 56,
          "input_2_4": 57,
          "input_3_4": 58,
          "sinput_4_4": 59,
          "input_5_4": 60,
          "finput_6_4": 61.8,
          "input_7_4": 62,
          "enum_256_1": 63,
          "enum_257_2": 64,
          "enum_259_4": 65,
          "heartbeat": 68,
          "heartbeat2": 69,
          "ibits_1000_1": 70,
          "coil_0": true,
          "coil_1": true,
          "coil_2": true,
          "coil_3": true,
          "coil_4": true,
          "coil_5": true,
          "coil_6": true,
          "coil_7": true,
          "break_test_1": true,
          "break_test_2": true,
          "surge_arrester": true,
          "fuse_monitoring": true,
          "door_latch": true,
          "disconnect_switch": true,
          "spare_1": true,
          "e_stop": true,
          "fire_relay": true,
          "trouble_relay": true,
          "component_connected": true
      }
      """
    And I wait 2 seconds
    And I send a fims pub to /components/test_server containing
      """
      {
          "hold_1_1": 1,
          "hold_1_2": 2,
          "hold_1_4": 3,
          "hold_2_1": 4,
          "hold_2_2": 5,
          "hold_2_4": 6,
          "shold_1_1": 7,
          "shold_1_2": 8,
          "shold_1_4": 9,
          "shold_2_1": 10,
          "shold_2_2": 11,
          "shold_2_4": 12,
          "fhold_1_2": 13.7,
          "fhold_1_4": 14.8,
          "scale_1_1": 16,
          "scale_1_2": 17,
          "scale_1_4": 18,
          "shift_1_1": 19,
          "shift_1_2": 20,
          "shift_1_4": 21,
          "test_id": 22,
          "inv_1_16": 23,
          "inv_1_4": 24,
          "multi_1": 25,
          "multi_2": 26,
          "multi_3": 27,
          "multi_4": 28,
          "multi_5": 29,
          "multi_6": 30,
          "multi_7": 31,
          "multi_8": 32,
          "multi_9": 33,
          "multi_10": 34,
          "multi_11": 35,
          "multi_12": 36,
          "multi_13": 37,
          "debounce_1": 38,
          "error_1": 39,
          "input_0_1": 40,
          "input_1_1": 41,
          "input_2_1": 42,
          "input_3_1": 43,
          "sinput_4_1": 44,
          "input_5_1": 45,
          "input_7_1": 46,
          "input_0_2": 47,
          "input_1_2": 48,
          "input_2_2": 49,
          "input_3_2": 50,
          "sinput_4_2": 51,
          "input_5_2": 52,
          "finput_6_2": 53.6,
          "input_7_2": 54,
          "input_0_4": 55,
          "input_1_4": 56,
          "input_2_4": 57,
          "input_3_4": 58,
          "sinput_4_4": 59,
          "input_5_4": 60,
          "finput_6_4": 61.8,
          "input_7_4": 62,
          "enum_256_1": 63,
          "enum_257_2": 64,
          "enum_259_4": 65,
          "heartbeat": 68,
          "heartbeat2": 69,
          "ibits_1000_1": 70,
          "coil_0": true,
          "coil_1": true,
          "coil_2": true,
          "coil_3": true,
          "coil_4": true,
          "coil_5": true,
          "coil_6": true,
          "coil_7": true,
          "break_test_1": true,
          "break_test_2": true,
          "surge_arrester": true,
          "fuse_monitoring": true,
          "door_latch": true,
          "disconnect_switch": true,
          "spare_1": true,
          "e_stop": true,
          "fire_relay": true,
          "trouble_relay": true,
          "component_connected": true
      }
      """
    Then I expect a fims set to /dbi/test_server/saved_registers/components/test_server within 1 seconds containing
      """
      {
          "hold_1_1": 1,
          "hold_1_2": 2,
          "hold_1_4": 3,
          "hold_2_1": 4,
          "hold_2_2": 5,
          "hold_2_4": 6,
          "shold_1_1": 7,
          "shold_1_2": 8,
          "shold_1_4": 9,
          "shold_2_1": 10,
          "shold_2_2": 11,
          "shold_2_4": 12,
          "fhold_1_2": 13.7,
          "fhold_1_4": 14.8,
          "scale_1_1": 16,
          "scale_1_2": 17,
          "scale_1_4": 18,
          "shift_1_1": 19,
          "shift_1_2": 20,
          "shift_1_4": 21,
          "test_id": 22,
          "inv_1_16": 23,
          "inv_1_4": 24,
          "multi_1": 25,
          "multi_2": 26,
          "multi_3": 27,
          "multi_4": 28,
          "multi_5": 29,
          "multi_6": 30,
          "multi_7": 31,
          "multi_8": 32,
          "multi_9": 33,
          "multi_10": 34,
          "multi_11": 35,
          "multi_12": 36,
          "multi_13": 37,
          "debounce_1": 38,
          "error_1": 39,
          "input_0_1": 40,
          "input_1_1": 41,
          "input_2_1": 42,
          "input_3_1": 43,
          "sinput_4_1": 44,
          "input_5_1": 45,
          "input_7_1": 46,
          "input_0_2": 47,
          "input_1_2": 48,
          "input_2_2": 49,
          "input_3_2": 50,
          "sinput_4_2": 51,
          "input_5_2": 52,
          "finput_6_2": 53.6,
          "input_7_2": 54,
          "input_0_4": 55,
          "input_1_4": 56,
          "input_2_4": 57,
          "input_3_4": 58,
          "sinput_4_4": 59,
          "input_5_4": 60,
          "finput_6_4": 61.8,
          "input_7_4": 62,
          "enum_256_1": 63,
          "enum_257_2": 64,
          "enum_259_4": 65,
          "heartbeat": 68,
          "heartbeat2": 69,
          "ibits_1000_1": 70,
          "coil_0": true,
          "coil_1": true,
          "coil_2": true,
          "coil_3": true,
          "coil_4": true,
          "coil_5": true,
          "coil_6": true,
          "coil_7": true,
          "break_test_1": true,
          "break_test_2": true,
          "surge_arrester": true,
          "fuse_monitoring": true,
          "door_latch": true,
          "disconnect_switch": true,
          "spare_1": true,
          "e_stop": true,
          "fire_relay": true,
          "trouble_relay": true
      }
      """
    When I kill modbus_client
    And I kill modbus_server
    And I start modbus_client with the config test_load_to_from_dbi_client.json
    And I start modbus_server with the config test_load_to_from_dbi_server.json
    Then I expect a fims get to /dbi/test_server/saved_registers/components/test_server within 1 seconds containing
      """
      (null)
      """
    And I expect a fims set to /interfaces/test_server/reply/components/test_server within 1 seconds containing
      """
      {
          "hold_1_1": 1,
          "hold_1_2": 2,
          "hold_1_4": 3,
          "hold_2_1": 4,
          "hold_2_2": 5,
          "hold_2_4": 6,
          "shold_1_1": 7,
          "shold_1_2": 8,
          "shold_1_4": 9,
          "shold_2_1": 10,
          "shold_2_2": 11,
          "shold_2_4": 12,
          "fhold_1_2": 13.7,
          "fhold_1_4": 14.8,
          "scale_1_1": 16,
          "scale_1_2": 17,
          "scale_1_4": 18,
          "shift_1_1": 19,
          "shift_1_2": 20,
          "shift_1_4": 21,
          "test_id": 22,
          "inv_1_16": 23,
          "inv_1_4": 24,
          "multi_1": 25,
          "multi_2": 26,
          "multi_3": 27,
          "multi_4": 28,
          "multi_5": 29,
          "multi_6": 30,
          "multi_7": 31,
          "multi_8": 32,
          "multi_9": 33,
          "multi_10": 34,
          "multi_11": 35,
          "multi_12": 36,
          "multi_13": 37,
          "debounce_1": 38,
          "error_1": 39,
          "input_0_1": 40,
          "input_1_1": 41,
          "input_2_1": 42,
          "input_3_1": 43,
          "sinput_4_1": 44,
          "input_5_1": 45,
          "input_7_1": 46,
          "input_0_2": 47,
          "input_1_2": 48,
          "input_2_2": 49,
          "input_3_2": 50,
          "sinput_4_2": 51,
          "input_5_2": 52,
          "finput_6_2": 53.6,
          "input_7_2": 54,
          "input_0_4": 55,
          "input_1_4": 56,
          "input_2_4": 57,
          "input_3_4": 58,
          "sinput_4_4": 59,
          "input_5_4": 60,
          "finput_6_4": 61.8,
          "input_7_4": 62,
          "enum_256_1": 63,
          "enum_257_2": 64,
          "enum_259_4": 65,
          "heartbeat": 68,
          "heartbeat2": 69,
          "ibits_1000_1": 70,
          "coil_0": true,
          "coil_1": true,
          "coil_2": true,
          "coil_3": true,
          "coil_4": true,
          "coil_5": true,
          "coil_6": true,
          "coil_7": true,
          "break_test_1": true,
          "break_test_2": true,
          "surge_arrester": true,
          "fuse_monitoring": true,
          "door_latch": true,
          "disconnect_switch": true,
          "spare_1": true,
          "e_stop": true,
          "fire_relay": true,
          "trouble_relay": true
      }
      """
    And I expect a fims pub to /components/test_client after 1 seconds containing
      """
      {
          "hold_1_1": 1,
          "hold_1_2": 2,
          "hold_1_4": 3,
          "hold_2_1": 4,
          "hold_2_2": 5,
          "hold_2_4": 6,
          "shold_1_1": 7,
          "shold_1_2": 8,
          "shold_1_4": 9,
          "shold_2_1": 10,
          "shold_2_2": 11,
          "shold_2_4": 12,
          "fhold_1_2": 13.7,
          "fhold_1_4": 14.8,
          "fshold_1_4": 0,
          "scale_1_1": 16,
          "scale_1_2": 17,
          "scale_1_4": 18,
          "shift_1_1": 119,
          "shift_1_2": 120,
          "shift_1_4": 121,
          "test_id": 22,
          "inv_1_16": 23,
          "inv_1_4": 24,
          "multi_1": 25,
          "multi_2": 26,
          "multi_3": 27,
          "multi_4": 28,
          "multi_5": 29,
          "multi_6": 30,
          "multi_7": 31,
          "multi_8": 32,
          "multi_9": 33,
          "multi_10": 34,
          "multi_11": 35,
          "multi_12": 36,
          "multi_13": 37,
          "debounce_1": 38,
          "error_1": 139,
          "input_0_1": 40,
          "input_1_1": 41,
          "input_2_1": 42,
          "input_3_1": 43,
          "sinput_4_1": 44,
          "input_5_1": 45,
          "input_7_1": 46,
          "input_0_2": 47,
          "input_1_2": 48,
          "input_2_2": 49,
          "input_3_2": 50,
          "sinput_4_2": 51,
          "input_5_2": 52,
          "finput_6_2": 53.6,
          "input_7_2": 54,
          "input_0_4": 55,
          "input_1_4": 56,
          "input_2_4": 57,
          "input_3_4": 58,
          "sinput_4_4": 59,
          "input_5_4": 60,
          "finput_6_4": 61.8,
          "input_7_4": 62,
          "enum_256_1": [{"value": 0, "string": "some_string"}],
          "enum_257_2": [{"value": 0, "string": "some_string"}],
          "enum_259_4": [{"value": 0, "string": "some_string"}],
          "bsinput_0_4": 0,
          "bsinput_1_4": 0,
          "heartbeat": 68,
          "heartbeat2": 69,
          "some_string":false,"another_string":false,"yet_another_string":false,"etc.":false,"some_string_2":false,"another_string_2":false,"yet_another_string_2":false,"etc._2":false,"some_string_3":false,"another_string_3":false,"yet_another_string_3":false,"etc._3":false,"bf_2007_1":[],"bf_2008_2":[],"bf_2010_4":[],"pack_1_first":[{"value":0, "string":"undefined"}],"pack_1_second":[{"value":0, "string":"undefined"}],
          "ibits_1000_1": 70,
          "coil_0": true,
          "coil_1": true,
          "coil_2": true,
          "coil_3": true,
          "coil_4": true,
          "coil_5": true,
          "coil_6": true,
          "coil_7": true,
          "break_test_1": true,
          "break_test_2": true,
          "surge_arrester": true,
          "fuse_monitoring": true,
          "door_latch": true,
          "disconnect_switch": true,
          "spare_1": true,
          "e_stop": true,
          "fire_relay": true,
          "trouble_relay": true,
          "component_connected": true
      }
      """