version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo Get submodules...
      - git init
      - git submodule update --init --recursive
      - echo Finished clone submodules...
      - echo Starting build...
  pre_build:
    commands:
      - echo Delete all submodules package-utility folders in pre-build...
      - rm -r ./site_controller/package_utility
      - rm -r ./fleet_manager/package_utility
      - rm -r ./dnp3_interface/package_utility
      - rm -r ./washer/package_utility
      - rm -r ./scheduler/package_utility
      - rm -r ./cops/package_utility
      - rm -r ./ftd/package_utility
      - rm -r ./cloud_sync/package_utility
      - rm -r ./dts/package_utility
      - rm -r ./twins/package_utility
      - rm -r ./echo/package_utility
      - rm -r ./overwatch/package_utility
      - rm -r ./metrics/package_utility
      - rm -r ./web_server/package_utility
      - rm -r ./web_ui/package_utility
      - echo All package_utility deleted, ready for build...
  build:
    commands:
      - echo Build started on `date`
      - echo running build.sh ...          
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`