version: 0.2

env:
  git-credential-helper: yes

phases:
  pre_build:
    commands:
      - echo Get submodules...
      - git init
      - git submodule update --init --recursive
      - echo Finished clone submodules...
      - echo Starting build...
  build:
    commands:
      - echo Build started on `date`
      - echo running build.sh ...          
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`