version: 0.2

env:
  parameter-store:
    ssh_key: "id_rsa"
    ssh_pub: "id_rsa.pub"

phases:
  install:
      commands:
        - echo Set Agent...
        - mkdir -p ~/.ssh
        - echo "$ssh_key" > ~/.ssh/id_rsa   
        - echo "$ssh_pub" > ~/.ssh/id_rsa.pub
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
        - git config --global url."git@github.com:".insteadOf "https://github.com/"
        - eval "$(ssh-agent -s)"
        - echo Starting build...
  build:
    commands:
      - echo Build started on `date`
      - ./cicd-scripts/build/build.sh
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: build-$(date +%Y-%m-%d)