version: 0.2

phases:
  install:
    commands:
      - echo Set Agent...
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa   
      - echo "$SSH_PUB" > ~/.ssh/id_rsa.pub
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - eval "$(ssh-agent -s)"
      - echo Checkout submodules...
      - ./git_checkout.sh -d .
  build:
    commands:
      - ./cicd-scripts/build/build.sh
artifacts:
  files:
    - '**/*'
  name: build-$(date +%Y-%m-%d)
  enable-symlinks: yes