version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo running build.sh ...
      - ./build.sh
      - cd $CODEBUILD_SRC_DIR
      - ./package.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: build-$(date +%Y-%m-%d)