version: 0.2

env:
  parameter-store:
    ssh_key: "id_ed25519"
    ssh_pub: "id_ed25519.pub"
    github_user: "github_user"
    github_token: "github_token"
phases:
  install:
    commands:
      - echo Start set ssh agent...
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - echo SSH Agent set...
  pre_build:
    commands:
      - echo Start clone submodules in pre_build...
      - git clone https://$github_user:$github_token@github.com/flexgen-power/web_ui.git
      - echo Finished clone submodules...
      - echo Starting build...
  build:
    commands:
      - echo Build started on `date`
      - echo running build.sh ...          
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`