version: 0.2

env:
  parameter-store:
    ssh_key: id_rsa
    ssh_pub: id_rsa.pub
phases:
  install:
    commands:
      - echo Start set ssh agent submodules...
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_rsa   
      - echo "$ssh_pub" > ~/.ssh/id_rsa.pub
      - chmod 600 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - echo SSH Agent set...
      - echo Start clone submodules...
      - git clone https://github.com/flexgen-power/web_ui.git
      - echo Finished clone submodules...
      - echo Starting build...
  pre_build:
    commands:
      - echo Nothing to do in pre-build...
  build:
    commands:
      - echo Build started on `date`
      - echo running build.sh ...          
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`