version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting build...
  build:
    commands:
      - echo Build started on `date`
      - echo running build.sh ...          
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`