version: '3'
services:
  config-fleet-manager-01:
    image: flexgen/fleet_manager:11.3.0.alpha.3
    container_name: config-fleet-manager-01
    hostname: config-fleet-manager-01
    ports:
      - 10000:9150
      - 9000:443
    networks:
      config-fleet-net:
        ipv4_address: 10.10.1.5
    tty: true
    volumes:
      - /home/hybridos/git/hybridos/config/horizon_power/config/fleet-manager/config:/home/staging
      - /home/hybridos/git/hybridos/config/horizon_power/config/fleet-manager/scripts:/home/utility
      - /home/hybridos/git/hybridos/config/horizon_power/config/fleet-manager/.secret:/home/secret
      - /home/hybridos/git/hybridos/virtual_site/scripts:/home/override

networks:
  config-fleet-net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24

