import {
  AppBar,
  AutoCompleteSearch,
  Badge,
  CardContainer,
  CardHeader,
  CardRow,
  Checkbox,
  Chip,
  DataGroup,
  DataPoint,
  DatePicker,
  DateTimePicker,
  Divider,
  Drawer,
  DrawerTab,
  Footer,
  Icon,
  IconButton,
  InfoDisplay,
  Label,
  Modal,
  MuiButton,
  Select,
  MuiTimePicker,
  PageLayout,
  PageLoadingIndicator,
  PureSearch,
  FlexSelect,
  Slider,
  Switch,
  Tab,
  Table,
  TextField,
  TimePicker,
  lightTheme,
  darkTheme,
  MaintModeSlider,
} from '@flexgen/storybook'

// FIXME: storybook should probably have consistent types
export interface IComponentHash {
  [key: string]: any
}

const storybookComponents: IComponentHash = {
  AppBar,
  AutoCompleteSearch,
  Badge,
  CardContainer,
  CardHeader,
  CardRow,
  Checkbox,
  Chip,
  DataGroup,
  DataPoint,
  DatePicker,
  DateTimePicker,
  Divider,
  Drawer,
  DrawerTab,
  Footer,
  Icon,
  IconButton,
  InfoDisplay,
  Label,
  Modal,
  MuiButton,
  Select,
  MuiTimePicker,
  PageLayout,
  PageLoadingIndicator,
  PureSearch,
  FlexSelect,
  Slider,
  Switch,
  Tab,
  Table,
  TextField,
  TimePicker,
  lightTheme,
  darkTheme,
  MaintModeSlider,
}

export default storybookComponents

const controlsSets = {
  onChange: [
    'Checkbox',
    'Slider',
    'Select',
    'Select',
    'PureSearch',
    'AutoCompleteSearch',
    'DatePicker',
    'DateTimePicker',
    'TimePicker',
    'MuiTimePicker',
  ],
  onClick: ['IconButton', 'MuiButton'],
  withConfirm: ['TextField', 'Switch', 'MaintModeSlider'],
}

export { controlsSets }
