version: 11.3.0.beta.4

modbus_client:
  apc_ups_modbus_client.json:
    ip: 192.168.10.250
    port: 10000
  acuvim_aux_modbus_client.json:
    ip: 192.168.10.250
    port: 10001
  ess_1_modbus_client.json:
    ip: 192.168.10.10
    port: 502
  ess_2_modbus_client.json:
    ip: 192.168.10.250
    port: 10006
  ess_3_modbus_client.json:
    ip: 192.168.10.250
    port: 10007
  sel_651r_modbus_client.json:
    ip: 192.168.10.250
    port: 20000
  sel_735_modbus_client.json:
    ip: 192.168.10.250
    port: 10003

dnp3_server: 
  site_sudden_valley_dnp3_server.json:
    ip: 0.0.0.0
    port: 20000

scheduler_server:
  configuration.json:
    port: 9000