dnp3_server:
  site_lima_dnp3_server.json:
    ip: 10.10.1.10
    port: 20000
modbus_client:
  acuvim_aux_modbus_client.json:
    ip: 192.168.10.250
    port: 10001
  apc_ups_modbus_client.json:
    ip: 192.168.10.250
    port: 10000
  ess_1_modbus_client.json:
    ip: 192.168.10.10
    port: 502
  ess_2_modbus_client.json:
    ip: 192.168.10.250
    port: 10006
  ess_3_modbus_client.json:
    ip: 192.168.10.250
    port: 10007
  sel_651r_modbus_client.json:
    ip: 192.168.10.250
    port: 20000
  sel_735_modbus_client.json:
    ip: 192.168.10.250
    port: 10003
scheduler_server:
  configuration.json:
    port: 9000
version: 12.0.0-beta.1
