mkdir -p libs
BUILD_DIR=./build/test
LIBS_DIR=./libs
CFLAGS="-Wall -Wno-psabi -I ./include"
# g++ -std=c++11 -o ${LIBS_DIR}/libfeed.so            $CFLAGS -fPIC -shared    src/feed.cpp -lcjson -lfims
# g++ -std=c++11 -o ${LIBS_DIR}/libess.so             $CFLAGS -fPIC -shared    src/ess.cpp  -lcjson -lfims
# g++ -std=c++11 -o ${LIBS_DIR}/libpcs.so             $CFLAGS -fPIC -shared    src/pcs.cpp  -lcjson -lfims
# g++ -std=c++11 -o ${LIBS_DIR}/libbms.so             $CFLAGS -fPIC -shared    src/bms.cpp  -lcjson -lfims
# g++ -std=c++11 -o ${BUILD_DIR}/md                   $CFLAGS    src/modbus_map.cpp src/modbus_dump.cpp -lcjson -lfims
# g++ -std=c++11 -o ${BUILD_DIR}/test_chan            $CFLAGS    test/test_chan.cpp         -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_ass          $CFLAGS    test/test_asset.cpp        -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_bms          $CFLAGS    test/test_bms.cpp          -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_pcs          $CFLAGS    test/test_pcs.cpp          -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_ess          $CFLAGS    test/test_ess.cpp          -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_func         $CFLAGS    test/functions.cpp           -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_fims         $CFLAGS    test/test_fims.cpp         -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_vmap0        $CFLAGS    test/test_vmap0.cpp        -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_valueChanged $CFLAGS    test/test_valueChanged.cpp -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_vmap_act0    $CFLAGS    test/test_vmap_act0.cpp   -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_vmap_act1    $CFLAGS    test/test_vmap_act1.cpp   -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_vmap_act2    $CFLAGS    test/test_vmap_act2.cpp   -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_vmap1        $CFLAGS    test/test_vmap1.cpp       -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_vmap_action  $CFLAGS    test/test_vmap_action.cpp -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_timer_chan   $CFLAGS    test/test_timer_chan.cpp  -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_preston      $CFLAGS    test/test_preston.cpp     -lpthread -lcjson -lfims
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_jimmy      $CFLAGS    test/test_jimmy.cpp         -lpthread -lcjson -lfims
 g++ -std=c++11 -g -o ${BUILD_DIR}/test_walker      $CFLAGS    test/test_walker.cpp         -lpthread -lcjson -lfims -lgtest
# g++ -std=c++11 -g -o ${BUILD_DIR}/test_phil      $CFLAGS    test/test_phil.cpp         -lpthread -lcjson -lfims -lgtest
