version: 11.3.0.alpha.3

modbus_client: 
  ess_1_bms_modbus_client.json: { ip: 192.168.13.5, port: 508}
  ess_1_pcs_modbus_client.json: { ip: 192.168.13.5, port: 509}

modbus_server: 
  ess_1_modbus_server.json: { ip: 0.0.0.0, port: 502}
