// TODO: fix this rule
/* eslint-disable max-lines */
import solarSample from './solarSample.json'
import solarOutput from './solarOutput.json'
import nakedOutput from './nakedOutput.json'

export const clothedTestCases = {
    sample: solarSample,
    expectedOutput: solarOutput,
}

export const nakedTestCases = {
    sample: {
        name: 'BESS Inverter Block 01',
        active_power: 0,
        active_power_setpoint_component_ctrl_cmd: 0,
        active_power_setpoint: 0,
        alarms: 0,
        apparent_power: 0,
        autobalancing_status: false,
        bms_fault: 0,
        com_status: 0,
        component_connected: false,
        current_l1: 0,
        current_l2: 0,
        current_l3: 0,
        dc_contactors_closed: false,
        emmu_fault: 0,
        faults: 0,
        frequency: 0,
        frequency_setpoint: 60,
        grid_mode: 0,
        local_bms_status: 0,
        max_temp: 0,
        min_temp: 0,
        modbus_heartbeat: 0,
        reactive_power: 0,
        reactive_power_setpoint_component_ctrl_cmd: 0,
        reactive_power_setpoint: 0,
        soc: 49.462364196777344,
        soh: 0,
        status: 'Stopped',
        system_chargeable_energy: 0,
        system_chargeable_power: 5500,
        system_dischargeable_energy: 0,
        system_dischargeable_power: 5500,
        voltage_dc: 0,
        voltage_l1_l2: 95600.234375,
        voltage_l2_l3: 0,
        voltage_l3_l1: 0,
        voltage_max: 0,
        voltage_min: 0,
        voltage_setpoint: 38333.33203125,
        lock_mode: {
            value: false,
            enabled: false,
            options: [
                { name: 'No', return_value: false },
                { name: 'Yes', return_value: true },
            ],
        },
        maint_mode: {
            value: false,
            enabled: true,
            options: [
                { name: 'No', return_value: false },
                { name: 'Yes', return_value: true },
            ],
        },
        start: {
            enabled: false,
            options: [
                { name: 'On', return_value: true },
                { name: 'Off', return_value: false },
            ],
        },
        stop: {
            enabled: false,
            options: [
                { name: 'On', return_value: true },
                { name: 'Off', return_value: false },
            ],
        },
        enter_standby: {
            enabled: false,
            options: [
                { name: 'On', return_value: true },
                { name: 'Off', return_value: false },
            ],
        },
        exit_standby: {
            enabled: false,
            options: [
                { name: 'On', return_value: true },
                { name: 'Off', return_value: false },
            ],
        },
        clear_faults: {
            enabled: false,
            options: [{ name: 'Clear Faults', return_value: true }],
        },
        limits_override: {
            value: false,
            enabled: false,
            options: [
                { name: 'On', return_value: true },
                { name: 'Off', return_value: false },
            ],
        },
        autobalancing_enable: {
            enabled: false,
            options: [
                { name: 'On', return_value: true },
                { name: 'Off', return_value: false },
            ],
        },
        autobalancing_disable: {
            enabled: false,
            options: [
                { name: 'On', return_value: true },
                { name: 'Off', return_value: false },
            ],
        },
        maint_active_power_setpoint: {
            value: 0,
            enabled: false,
            options: [],
        },
        maint_reactive_power_setpoint: {
            value: 0,
            enabled: false,
            options: [],
        },
    },
    metadata: {
        alarms: { alarmFields: [], faultFields: [] },
        batchControls: [
            {
                inputType: 'switch',
                name: 'Maintenance Mode',
                scalar: '',
                units: '',
                uri: '/maint_mode',
            },
        ],
        controls: [
            {
                inputType: 'switch',
                name: 'Maintenance Mode',
                scalar: '1',
                units: '',
                uri: '/maint_mode',
            },
            {
                inputType: 'button',
                name: 'Start',
                scalar: '1',
                units: '',
                uri: '/start',
            },
            {
                inputType: 'button',
                name: 'Stop',
                scalar: '1',
                units: '',
                uri: '/stop',
            },
            {
                inputType: 'button',
                name: 'Enter Standby',
                scalar: '1',
                units: '',
                uri: '/enter_standby',
            },
            {
                inputType: 'button',
                name: 'Exit Standby',
                scalar: '1',
                units: '',
                uri: '/exit_standby',
            },
            {
                inputType: 'button',
                name: 'Clear Faults',
                scalar: '1',
                units: '',
                uri: '/clear_faults',
            },
            {
                inputType: 'switch',
                name: 'Limits Override',
                scalar: '1',
                units: '',
                uri: '/limits_override',
            },
            {
                inputType: 'number',
                name: 'Active Power Setpoint',
                scalar: '1000',
                units: 'MW',
                uri: '/maint_active_power_setpoint',
            },
            {
                inputType: 'number',
                name: 'Reactive Power Setpoint',
                scalar: '1000',
                units: 'MW',
                uri: '/maint_reactive_power_setpoint',
            },
            {
                inputType: 'button',
                name: 'Close DC Contactors',
                scalar: '1',
                units: '',
                uri: '/close_dc_contactors',
            },
            {
                inputType: 'button',
                name: 'Open DC Contactors',
                scalar: '1',
                units: '',
                uri: '/open_dc_contactors',
            },
        ],
        info: {
            alarmFields: ['alarms', 'com_status', 'ess_alarms'],
            assetKey: 'ESS_tab',
            baseURI: '/ess',
            extension: '/ess_',
            faultFields: ['faults', 'bms_fault', 'emmu_fault', 'ess_faults'],
            hasBatchControls: true,
            hasMaintenanceActions: false,
            hasSummary: false,
            itemName: 'BESS Inverter Block',
            name: 'ESS_New',
            numberOfItems: '4',
            sourceURI: '/assets',
        },
        statuses: [
            {
                name: 'Active Power',
                scalar: '1000',
                units: 'MW',
                uri: '/active_power',
            },
            {
                name: 'Active Power Setpoint',
                scalar: '1000',
                units: 'MW',
                uri: '/active_power_setpoint',
            },
            {
                name: 'Apparent Power',
                scalar: '1000',
                units: 'MVA',
                uri: '/apparent_power',
            },
            {
                name: 'Auto Balancing Status',
                scalar: '1',
                units: '',
                uri: '/autobalancing_status',
            },
            {
                name: 'Component Connection Status',
                scalar: '1',
                units: '',
                uri: '/component_connected',
            },
            {
                name: 'L1 AC Current',
                scalar: '1',
                units: 'A',
                uri: '/current_l1',
            },
            {
                name: 'L2 AC Current\t',
                scalar: '1',
                units: 'A',
                uri: '/current_l2',
            },
            {
                name: 'L3 AC Current',
                scalar: '1',
                units: 'A',
                uri: '/current_l3',
            },
            {
                name: 'DC Contactors Closed',
                scalar: '1',
                units: '',
                uri: '/dc_contactors_closed',
            },
            {
                name: 'Frequency',
                scalar: '1',
                units: 'Hz',
                uri: '/frequency',
            },
            {
                name: 'Frequency Setpoint',
                scalar: '1',
                units: 'Hz',
                uri: '/frequency_setpoint',
            },
            {
                name: 'Grid_mode',
                scalar: '1',
                units: '',
                uri: '/grid_mode',
            },
            {
                name: 'Racks In Service\t',
                scalar: '1',
                units: '',
                uri: '/local_bms_status',
            },
            {
                name: 'Current Highest Cell Temp\t',
                scalar: '1',
                units: 'C',
                uri: '/max_temp',
            },
            {
                name: 'Current Lowest Cell Temp\t',
                scalar: '1',
                units: 'C',
                uri: '/min_temp',
            },
            {
                name: 'Reactive Power',
                scalar: '1000',
                units: 'MVAR',
                uri: '/reactive_power',
            },
            {
                name: 'Reactive Power Setpoint\t',
                scalar: '1000',
                units: 'MVAR',
                uri: '/reactive_power_setpoint',
            },
            {
                name: 'State of Charge\t',
                scalar: '1',
                units: '%',
                uri: '/soc',
            },
            {
                name: 'State of Health\t',
                scalar: '1',
                units: '%',
                uri: '/soh',
            },
            { name: 'Status', scalar: '1', units: '', uri: '/status' },
            {
                name: 'System Chargeable Energy\t',
                scalar: '1000',
                units: 'MWh',
                uri: '/system_chargeable_energy',
            },
            {
                name: 'System Chargeable Power\t',
                scalar: '1000',
                units: 'MW',
                uri: '/system_chargeable_power',
            },
            {
                name: 'System Dischargeable Energy\t',
                scalar: '1000',
                units: 'MWh',
                uri: '/system_dischargeable_energy',
            },
            {
                name: 'System Dischargeable Power\t',
                scalar: '1000',
                units: 'MW',
                uri: '/system_dischargeable_power',
            },
            {
                name: 'L1-L2 AC Voltage',
                scalar: '1',
                units: 'V',
                uri: '/voltage_l1_l2',
            },
            {
                name: 'L2-L3 AC Voltage',
                scalar: '1',
                units: 'V',
                uri: '/voltage_l2_l3',
            },
            {
                name: 'L3-L1 AC Voltage',
                scalar: '1',
                units: 'V',
                uri: '/voltage_l3_l1',
            },
            {
                name: 'Maximum Voltage',
                scalar: '1',
                units: 'V',
                uri: '/voltage_max',
            },
            {
                name: 'Minimum Voltage',
                scalar: '1',
                units: 'V',
                uri: '/voltage_min',
            },
            {
                name: 'Voltage Setpoint',
                scalar: '1',
                units: 'V',
                uri: '/voltage_setpoint',
            },
        ],
        summary: [],
        summaryControls: [],
    },
    expectedOutput: nakedOutput,
}
