export const AssetsDescriptions = {
    assetsResponse: 'List of asset tabs from dbi.',
    addAssetResponse: 'Add asset to dbi.',
    assets: 'Array of asset objects',
    summaryControls: 'Array of Summary Controls associated with this asset',
    summary: 'Array of summary objects associated with this asset',
    statuses: 'Array of statuses associated with this asset',
    info: 'Array of info objects associated with this asset',
    controls: 'Array of controls associated with this asset',
    batchControls: 'Array of batch controls associated with this asset',
    alarms: 'Array of information about alarms and faults associated with this asset',
    alarmFields: 'Array of alarm fields associated with this asset',
    faultFields: 'Array of fault fields associated with this asset',
    controlInputType: 'Input type of a particular control',
    controlName: 'Name of a control, what is displayed to the UI',
    controlScalar: 'Scalar used for particular control',
    controlUnits: 'Unit used for a particular control',
    controlURI: 'URI associated with a particular control',
    statusName: 'Name of a status, what is displayed to the UI',
    statusScalar: 'Scalar used for particular status',
    statusUnits: 'Unit used for particular status',
    statusURI: 'URI associated with a particular status',
}

export const ASSETS_SERVICE = 'AssetsService'
