// TODO: fix this rule
/* eslint-disable max-lines */
import { faker } from '@faker-js/faker'
import { FimsMsg } from '../../../../fims/interfaces/fims.interface'

export default (): FimsMsg => {
    return {
        method: 'a',
        uri: 'b',
        replyto: 'c',
        username: 'd',
        body: {
            name: 'Solar Inverter 1',
            active_power: {
                value: faker.datatype.number({ min: 0, max: 1000 }), // 36.94
                name: 'Active Power',
                unit: 'W',
                scaler: 1000,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            active_power_setpoint: {
                active_power_setpoint_component_ctrl_cmd: 0,
                value: 0,
                name: 'Active Power Setpoint',
                unit: 'W',
                scaler: 1000,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            alarms: {
                value: 0,
                name: 'Alarms',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Int',
                ui_type: 'alarm',
            },
            apparent_power: {
                value: 0,
                name: 'Apparent Power',
                unit: 'VA',
                scaler: 1000,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            component_connected: {
                value: false,
                name: 'Component Connection Status',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Bool',
                ui_type: 'status',
            },
            current_l1: {
                value: 0,
                name: 'L1 AC Current',
                unit: 'A',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            current_l2: {
                value: 0,
                name: 'L2 AC Current',
                unit: 'A',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            current_l3: {
                value: 0,
                name: 'L3 AC Current',
                unit: 'A',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            faults: {
                value: 0,
                name: 'Faults',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Int',
                ui_type: 'fault',
            },
            modbus_connected: {
                value: false,
                name: 'Modbus Connection Status',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Bool',
                ui_type: 'status',
            },
            modbus_heartbeat: {
                value: 0,
                name: 'Modbus Heartbeat',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Int',
                ui_type: 'none',
            },
            power_factor: {
                value: 0,
                name: 'Power Factor',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            power_factor_setpoint: {
                value: 1,
                name: 'Power Factor Setpoint',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            reactive_power: {
                value: 0,
                name: 'Reactive Power',
                unit: 'VAR',
                scaler: 1000,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            reactive_power_mode: {
                value: 1072,
                name: 'Reactive Power Mode',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            reactive_power_setpoint: {
                reactive_power_setpoint_component_ctrl_cmd: 0,
                value: 0,
                name: 'Reactive Power Setpoint',
                unit: 'W',
                scaler: 1000,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            status: {
                value: 'Stopped',
                name: 'Status',
                unit: '',
                scaler: 1,
                enabled: true,
                type: 'Status',
                ui_type: 'status',
                options: [
                    {
                        name: 'Stopped',
                        return_value: 0,
                    },
                ],
            },
            voltage_l1_l2: {
                value: 0,
                name: 'L1-L2 AC Voltage',
                unit: 'V',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            voltage_l1_n: {
                value: 0,
                name: 'L1 AC Voltage',
                unit: 'V',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            voltage_l2_l3: {
                value: 0,
                name: 'L2-L3 AC Voltage',
                unit: 'V',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            voltage_l2_n: {
                value: 0,
                name: 'L2 AC Voltage',
                unit: 'V',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            voltage_l3_l1: {
                value: 0,
                name: 'L3-L1 AC Voltage',
                unit: 'V',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            voltage_l3_n: {
                value: 0,
                name: 'L3 AC Voltage',
                unit: 'V',
                scaler: 1,
                enabled: true,
                type: 'Float',
                ui_type: 'status',
            },
            maint_mode: {
                name: 'Maintenance Mode',
                unit: '',
                scaler: 1,
                ui_type: 'control',
                type: 'enum_slider',
                value: false,
                enabled: true,
                options: [
                    {
                        name: 'No',
                        return_value: false,
                    },
                    {
                        name: 'Yes',
                        return_value: true,
                    },
                ],
            },
            clear_faults: {
                name: 'Clear Faults',
                unit: '',
                scaler: 1,
                ui_type: 'control',
                type: 'enum_button',
                enabled: false,
                options: [
                    {
                        name: 'Clear Faults',
                        return_value: true,
                    },
                ],
            },
            start: {
                name: 'Start',
                unit: '',
                scaler: 1,
                ui_type: 'control',
                type: 'enum_button',
                enabled: false,
                options: [
                    {
                        name: 'On',
                        return_value: true,
                    },
                    {
                        name: 'Off',
                        return_value: false,
                    },
                ],
            },
            stop: {
                name: 'Stop',
                unit: '',
                scaler: 1,
                ui_type: 'control',
                type: 'enum_button',
                enabled: false,
                options: [
                    {
                        name: 'On',
                        return_value: true,
                    },
                    {
                        name: 'Off',
                        return_value: false,
                    },
                ],
            },
            enter_standby: {
                name: 'Enter Standby',
                unit: '',
                scaler: 1,
                ui_type: 'control',
                type: 'enum_button',
                enabled: false,
                options: [
                    {
                        name: 'On',
                        return_value: true,
                    },
                    {
                        name: 'Off',
                        return_value: false,
                    },
                ],
            },
            exit_standby: {
                name: 'Exit Standby',
                unit: '',
                scaler: 1,
                ui_type: 'control',
                type: 'enum_button',
                enabled: false,
                options: [
                    {
                        name: 'On',
                        return_value: true,
                    },
                    {
                        name: 'Off',
                        return_value: false,
                    },
                ],
            },
            maint_active_power_setpoint: {
                name: 'Active Power Setpoint',
                unit: 'W',
                scaler: 1000,
                ui_type: 'control',
                type: 'number',
                value: 0,
                enabled: false,
                options: [],
            },
            maint_reactive_power_setpoint: {
                name: 'Reactive Power Setpoint',
                unit: 'VAR',
                scaler: 1000,
                ui_type: 'control',
                type: 'number',
                value: 0,
                enabled: false,
                options: [],
            },
        },
    }
}
