version: 11.3.0.alpha.3

dnp3_client: 
  site_lima_dnp3_client.json: { ip: 10.10.1.10, port: 502}
  site_sudden_valley_dnp3_client.json: { ip: 10.10.1.11, port: 502}

dnp3_server: 
  lima_dnp3_server.json: { ip: 0.0.0.0, port: 502}
  sudden_valley_dnp3_server.json: { ip: 0.0.0.0, port: 503}
