package go_metrics

import (
	"testing"
)

type ParseTest struct {
	equation      string
	vars          []string
	errorExpected bool
	resultType    DataType
}

var ParseTests = []ParseTest{
	{
		equation:      "bool1",
		vars:          []string{"bool1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1",
		vars:          []string{"uint1"},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "int1",
		vars:          []string{"int1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "float1",
		vars:          []string{"float1"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1",
		vars:          []string{"string1"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "bool1 + bool2",
		vars:          []string{"bool1", "bool2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 + bool2",
		vars:          []string{"uint1", "bool2"},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "int1 + bool2",
		vars:          []string{"int1", "bool2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "float1 + bool2",
		vars:          []string{"float1", "bool2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1 + bool2",
		vars:          []string{"string1", "bool2"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "bool1 + uint2",
		vars:          []string{"bool1", "uint2"},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "uint1 + uint2",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "int1 + uint2",
		vars:          []string{"int1", "uint2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "float1 + uint2",
		vars:          []string{"float1", "uint2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1 + uint2",
		vars:          []string{"string1", "uint2"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "bool1 + int2",
		vars:          []string{"bool1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "uint1 + int2",
		vars:          []string{"uint1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "int1 + int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "float1 + int2",
		vars:          []string{"float1", "int2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1 + int2",
		vars:          []string{"string1", "int2"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "bool1 + float2",
		vars:          []string{"bool1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "uint1 + float2",
		vars:          []string{"uint1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "int1 + float2",
		vars:          []string{"int1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "float1 + float2",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1 + float2",
		vars:          []string{"string1", "float2"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "string1 == float2",
		vars:          []string{"string1", "float2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "!bool1",
		vars:          []string{"bool1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "!nonexistant",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "^bool1",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "!string1",
		vars:          []string{"string1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "-string1",
		vars:          []string{"string1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Add(float1,5.0)",
		vars:          []string{"float1"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Sub(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Sub(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Sub(float1,float2,int1)",
		vars:          []string{"float1", "float2", "int1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Mult(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Mult(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Div(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Div(float1,float2,5.0)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Div(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Mod(int1,int2)",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Mod(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Mod(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Mod(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Mod(bool1,bool2)",
		vars:          []string{"bool1", "bool2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseAnd(int1,int2)",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "BitwiseAnd(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseAnd(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseOr(int1,int2)",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "BitwiseOr(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseOr(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseXor(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseXor(int1,int2)",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "BitwiseXor(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "LeftShift(int1,int2)",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "LeftShift(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "LeftShift(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "LeftShift(bool1,bool2)",
		vars:          []string{"bool1", "bool2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "LeftShift(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "RightShift(int1,int2)",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "RightShift(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "RightShift(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "RightShift(bool1,bool2)",
		vars:          []string{"bool1", "bool2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "RightShift(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseAndNot(int1,int2)",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "BitwiseAndNot(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseAndNot(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "BitwiseAndNot(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "And(int1,string1)",
		vars:          []string{"int1", "string1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Or(int1,string1)",
		vars:          []string{"int1", "string1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Not(int1,string1)",
		vars:          []string{"int1", "string1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Equal(uint1,uint2)",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Equal(uint1)",
		vars:          []string{"uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "NotEqual(uint1,uint2)",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "NotEqual(uint1)",
		vars:          []string{"uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "LessThan(uint1,uint2,5)",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "LessThan(uint1)",
		vars:          []string{"uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "GreaterThan(uint1,uint2,5)",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "GreaterThan(uint1)",
		vars:          []string{"uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "LessThanOrEqual(uint1,uint2,5)",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "LessThanOrEqual(uint1)",
		vars:          []string{"uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "GreaterThanOrEqual(uint1,uint2,5)",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "GreaterThanOrEqual(uint1)",
		vars:          []string{"uint1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Root(int1,3)",
		vars:          []string{"int1"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Root(2)",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Root(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pow(2)",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pow(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pow(int1,2)",
		vars:          []string{"int1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Max(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Max(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Min(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Min(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Avg(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Avg(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Avg(bool1,bool2)",
		vars:          []string{"bool1", "bool2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Floor(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Floor(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Ceil(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Ceil(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Sqrt(int1,int2,uint1)",
		vars:          []string{"int1", "int2", "uint1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Sqrt(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pct(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Pct(float1,float2,5.0)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pct(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "FloorDiv(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "FloorDiv(float1,float2,5.0)",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "FloorDiv(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Abs(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Abs(float1,float2,5.0)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Abs(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Round(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Round(float1,float2,5.0)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Round(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Bool(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Int(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Uint(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "Float(int1,uint2)",
		vars:          []string{"int1", "uint2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "String(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "Integrate(float1)",
		vars:          []string{"float1"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Integrate(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Integrate()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Integrate(string1)",
		vars:          []string{"string1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Integrate(string1,float2)",
		vars:          []string{"string1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "CurrentTimeMilliseconds()",
		vars:          []string{},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "CurrentTimeMilliseconds(int1)",
		vars:          []string{"int1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Time()",
		vars:          []string{},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "Time(int1)",
		vars:          []string{"int1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "MillisecondsSince()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "MillisecondsSince(int1)",
		vars:          []string{"int1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "MillisecondsSince(string1)",
		vars:          []string{"string1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "MillisecondsToRFC3339()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "MillisecondsToRFC3339(int1)",
		vars:          []string{"int1"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "MillisecondsToRFC3339(string1)",
		vars:          []string{"string1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "RFC3339()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "RFC3339(int1)",
		vars:          []string{"int1"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "RFC3339(string1)",
		vars:          []string{"string1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Srff(string1,string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Srff(float1,float2)",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Srff(float1,float2,int1)",
		vars:          []string{"float1", "float2", "int1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Rss(float1,float2,int1)",
		vars:          []string{"float1", "float2", "int1"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "Rss(string1,string2,int1)",
		vars:          []string{"string1", "string2", "int1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Rss()",
		vars:          []string{},
		errorExpected: false,
		resultType:    NIL,
	},
	{
		equation:      "SelectN(float1,string1,int1)",
		vars:          []string{"float1", "string1", "int1"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "SelectN()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "SelectN(string1, string2)",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "SelectorN(float1,string1,int1)",
		vars:          []string{"float1", "string1", "int1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "SelectorN()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "SelectN(float1,string1,int1)",
		vars:          []string{"float1", "string1", "int1"},
		errorExpected: false,
		resultType:    STRING,
	},
	{
		equation:      "SelectN()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pulse(bool1, bool2, int1)",
		vars:          []string{"bool1", "bool2", "int1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Pulse(bool1)",
		vars:          []string{"bool1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pulse(string1, int1, int2)",
		vars:          []string{"string1", "int1", "int2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pulse(bool1, string1, int1)",
		vars:          []string{"bool1", "string1", "int1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pulse(bool1, float1, string1)",
		vars:          []string{"bool1", "float1", "string1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Pulse(bool1, bool2, int1)",
		vars:          []string{"bool1", "bool2", "int1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "IfElse(bool1, bool2, int1)",
		vars:          []string{"bool1", "bool2", "int1"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "IfElse()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Count()",
		vars:          []string{},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "Count(bool1, bool2)",
		vars:          []string{"bool1", "bool2"},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "CombineBits(bool1, bool2)",
		vars:          []string{"bool1", "bool2"},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "CombineBits()",
		vars:          []string{},
		errorExpected: false,
		resultType:    UINT,
	},
	{
		equation:      "In(3, bool1)",
		vars:          []string{"bool1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "In()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "In(3)",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "NotAFunction(bool1, bool2, int1)",
		vars:          []string{"bool1", "bool2", "int1"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "IfElse(Bool(nonexistant), bool2, int1)",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "Attribute(enabled == true)",
		vars:          []string{"enabled", "true"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Attribute(nonexistant == true)",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1-float2",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1-string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1*float2",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1*string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1/float2",
		vars:          []string{"float1", "float2"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "string1 / string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 % int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "float1 % float2",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "string1 % string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "bool1 % bool2",
		vars:          []string{"bool1", "bool2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 & int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "string1 & string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1 & float2",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 | int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "string1 | string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1 | float2",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 ^ int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "string1 ^ string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1 ^ float2",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 << int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "string1 << string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1 << float2",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "bool1 << bool2",
		vars:          []string{"bool1", "bool2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 >> int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "string1 >> string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "float1 >> float2",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "bool1 >> bool2",
		vars:          []string{"bool1", "bool2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 &^ int2",
		vars:          []string{"int1", "int2"},
		errorExpected: false,
		resultType:    INT,
	},
	{
		equation:      "float1 &^ float2",
		vars:          []string{"float1", "float2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "string1 &^ string2",
		vars:          []string{"string1", "string2"},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "int1 && string1",
		vars:          []string{"int1", "string1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "int1 || string1",
		vars:          []string{"int1", "string1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 == uint2",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 != uint2",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 < uint2",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 > uint2",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 <= uint2",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 >= uint2",
		vars:          []string{"uint1", "uint2"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "Sub() >= uint2",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "uint2 >= Sub()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "func(){uint1 == uint2}()",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "uint1 == 'c'",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      `uint1 == "string"`,
		vars:          []string{"uint1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 == 3.14",
		vars:          []string{"uint1"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "uint1 == 3.14i",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      `string1[0:5]`,
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
	{
		equation:      "input1@enabled || input2@enabled",
		vars:          []string{"input1@enabled", "input2@enabled"},
		errorExpected: false,
		resultType:    BOOL,
	},
	{
		equation:      "(uint1 + uint2)/float1",
		vars:          []string{"uint1", "uint2", "float1"},
		errorExpected: false,
		resultType:    FLOAT,
	},
	{
		equation:      "☺",
		vars:          []string{},
		errorExpected: true,
		resultType:    NIL,
	},
}

func TestParse(t *testing.T) {
	InputScope = map[string][]Union{
		"bool1":          {{tag: BOOL, b: true}},
		"bool2":          {{tag: BOOL, b: true}},
		"uint1":          {{tag: UINT, ui: 0}},
		"uint2":          {{tag: UINT, ui: 0}},
		"int1":           {{tag: INT, i: 0}},
		"int2":           {{tag: INT, i: 0}},
		"float1":         {{tag: FLOAT, f: 0}},
		"float2":         {{tag: FLOAT, f: 0}},
		"string1":        {{tag: STRING, s: ""}},
		"string2":        {{tag: STRING, s: ""}},
		"input1@enabled": {{tag: BOOL, b: true}},
	}
	allPossibleAttributes = make(map[string][]string, 0)
	allPossibleAttributes["enabled"] = []string{"input1@enabled"}
	var output *Expression
	output = &Expression{
		Vars: []string{},
	}
	var err error
	for _, test := range ParseTests {
		output, err = Parse(test.equation, "")
		if err == nil && test.errorExpected {
			t.Errorf("%s: no error when there should have been\n", test.equation)
			continue
		} else if err != nil && !test.errorExpected {
			t.Errorf("%s: got an err when there should not have been an error; error was: %v\n", test.equation, err)
			continue
		}
		if len(output.Vars) != len(test.vars) {
			t.Errorf("%s: output vars %v not equal to expected vars %v\n", test.equation, output.Vars, test.vars)
		} else {
			for i := range output.Vars {
				if output.Vars[i] != test.vars[i] {
					t.Errorf("%s: output var %v not equal to expected var %v\n", test.equation, output.Vars[i], test.vars[i])
				}
			}
		}
		if output.ResultType != test.resultType {
			t.Errorf("%s: output result type %v not equal to expected %v\n", test.equation, output.ResultType, test.resultType)
		}

	}
}
