<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v8="http://ads.caiso.com/api/webservices/dispatch/v8"><soapenv:Header/><soapenv:Body><v8:#query soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><batchUID xsi:type="xsd:string">#batchUID</batchUID></v8:#query></soapenv:Body></soapenv:Envelope>