dnp3_client:
  sel_411l_dnp3_client.json:
    ip: 0.0.0.0
    port: 20000
  sel_487e_dnp3_client.json:
    ip: 0.0.0.0
    port: 20001
dnp3_server:
  site_sudden_valley_dnp3_server.json:
    ip: 10.10.1.11
    port: 20000
modbus_client:
  apc_ups_modbus_client.json:
    ip: 192.168.10.250
    port: 10000
  ess_10_modbus_client.json:
    ip: 192.168.10.250
    port: 10014
  ess_11_modbus_client.json:
    ip: 192.168.10.250
    port: 10015
  ess_12_modbus_client.json:
    ip: 192.168.10.250
    port: 10016
  ess_1_modbus_client.json:
    ip: 192.168.10.10
    port: 502
  ess_2_modbus_client.json:
    ip: 192.168.10.250
    port: 10006
  ess_3_modbus_client.json:
    ip: 192.168.10.250
    port: 10007
  ess_4_modbus_client.json:
    ip: 192.168.10.250
    port: 10008
  ess_5_modbus_client.json:
    ip: 192.168.10.250
    port: 10009
  ess_6_modbus_client.json:
    ip: 192.168.10.250
    port: 10010
  ess_7_modbus_client.json:
    ip: 192.168.10.250
    port: 10011
  ess_8_modbus_client.json:
    ip: 192.168.10.250
    port: 10012
  ess_9_modbus_client.json:
    ip: 192.168.10.250
    port: 10013
  sel_351_1_modbus_client.json:
    ip: 192.168.10.250
    port: 10001
  sel_351_2_modbus_client.json:
    ip: 192.168.10.250
    port: 10002
  sel_735_modbus_client.json:
    ip: 192.168.10.250
    port: 10003
scheduler_server:
  configuration.json:
    port: 9000
version: 12.0.0-beta.1
