version: 11.3.1.alpha.1

modbus_server: 
  apc_ups_modbus_server.json:
    ip: 0.0.0.0
    port: 10000
  ess_1_bms_modbus_server.json:
    ip: 0.0.0.0
    port: 5030
  ess_1_pcs_modbus_server.json:
    ip: 0.0.0.0
    port: 5031
  ess_2_modbus_server.json:
    ip: 0.0.0.0
    port: 10006
  ess_3_modbus_server.json:
    ip: 0.0.0.0
    port: 10007
  ess_4_modbus_server.json:
    ip: 0.0.0.0
    port: 10008
  ess_5_modbus_server.json:
    ip: 0.0.0.0
    port: 10009
  ess_6_modbus_server.json:
    ip: 0.0.0.0
    port: 10010
  ess_7_modbus_server.json:
    ip: 0.0.0.0
    port: 10011
  ess_8_modbus_server.json:
    ip: 0.0.0.0
    port: 10012
  ess_9_modbus_server.json:
    ip: 0.0.0.0
    port: 10013
  ess_10_modbus_server.json:
    ip: 0.0.0.0
    port: 10014
  ess_11_modbus_server.json:
    ip: 0.0.0.0
    port: 10015
  ess_12_modbus_server.json:
    ip: 0.0.0.0
    port: 10016
  sel_351_1_modbus_server.json:
    ip: 0.0.0.0
    port: 10001
  sel_351_1_modbus_server.json:
    ip: 0.0.0.0
    port: 10002
  sel_735_modbus_client.json:
    ip: 192.168.12.250
    port: 10003


dnp3_server:
  sel_411l_dnp3_server.json:
    ip: 0.0.0.0
    port: 20000
  sel_487e_dnp3_server.json:
    ip: 0.0.0.0
    port: 20001
