#!/usr/bin/env groovy

//See package_utility/README for a list of valid inputs

myJobPipeline {

    //Which OS would you like to build on?
    imageNames=["centos7"]

    //Does the image need a special tag?
    //imageTag="devel-10.3.0"
    //imageTag="devel-10.3.0-fims-3.0.1.rc"
    imageTag="devel-11.1.0"
    //Does the image need a special tag?
    // imageTag="devel-10.3.0-fims-3.0.0"
    // imageTag="base"
    // imageTag="devel-10.3.0-fims-3.0.1.rc"

    //Run unit tests?
    unitTestStage=false

    //Run regression Tests?
    regTestStage=false

    //Which repository will RPMs be uploaded to?
    uploadRepo="flex"

    //Will a release of this repo need to trigger a docker image build?
    dockerBuild=false
    dockerImageName=""
    dockerTag=""
}